config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  resources :categories, only: [:index, :show]
  resources :sub_categories, only: :show
  resources :products, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # ADMIN
  get "/deltadmin", to: 'deltadmin/pages#dashboard'
  namespace :deltadmin do
    resources :categories
    resources :sub_categories
    resources :users
    resources :products
  end


end

app/views/shared/_admin_navbar.html.erb
<div class="wrapper">
  <div class="admin-navbar">
    <p><%= link_to "Dashboard", deltadmin_path, class: "link-name" %></p>
    <p>|</p>
    <p><%= link_to "Catégorie", deltadmin_categories_path, class: "link-name" %></p>
    <p>|</p>
    <p><%= link_to "Sous-catégorie", deltadmin_sub_categories_path, class: "link-name" %></p>
    <p>|</p>
    <p><%= link_to "Produits", deltadmin_products_path, class: "link-name" %></p>
    <p>|</p>
    <p><%= link_to "Utilisateurs", deltadmin_users_path, class: "link-name" %></p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <p class="text-center">© 2016 Delta Microscopies, All Rights Reserved.</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to 'Nos produits', categories_path, class: 'navbar-wagon-item navbar-wagon-link' %>
    <%= link_to 'Qui sommes nous', categories_path, class: 'navbar-wagon-item navbar-wagon-link' %>
    <%= link_to 'Nous contacter', categories_path, class: 'navbar-wagon-item navbar-wagon-link' %>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag 'profile_default.jpg', class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <% if current_user.admin == true %>
              <li>
                <%= link_to deltadmin_path do %>
                  <i class="fa fa-wrench"></i> <%= t(".admin", default: "Deltadmin") %>
              <% end %>
            </li>
            <% end %>
          <!--   <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li> -->
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <% link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>