config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  resources :categories, only: [:index, :show]
  resources :sub_categories, only: :show
  resources :products, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # ADMIN
  get "/deltadmin", to: 'deltadmin/pages#dashboard'
  namespace :deltadmin do
    resources :categories
    resources :sub_categories
    resources :users
    resources :products
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/deltadmin/application_controller.rb
class Deltadmin::ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  layout 'deltadmin'
end

app/controllers/deltadmin/categories_controller.rb
class Deltadmin::CategoriesController < Deltadmin::ApplicationController
  before_action :set_category , only: [:show, :edit, :update, :destroy]



  def index
    @categories = Category.all.order(name: 'ASC')
    @sub_categories = SubCategory.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to deltadmin_category_path(@category)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to deltadmin_category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to deltadmin_categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :photo)
  end

end

app/controllers/deltadmin/pages_controller.rb
class Deltadmin::PagesController < Deltadmin::ApplicationController
  skip_before_action :authenticate_user!, only: [ :admin ]

  def dashboard
  end
end

app/controllers/deltadmin/products_controller.rb
class Deltadmin::ProductsController < Deltadmin::ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @filterrific = initialize_filterrific(
      Product,
      params[:filterrific],
      select_options: {
        sorted_by: Product.options_for_sorted_by,
        sub_category: SubCategory.options_for_select
      },
    ) or return
    @products = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end

  end


  def new
    @product = Product.new
  end

  def create
    @product = product.new(product_params)

    if @product.save
      redirect_to deltadmin_product_path(@product)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to deltadmin_product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to deltadmin_products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :active, :supplier_ref, :delta_ref, :sell_price, :buy_price, :product_number, :supplier_id, :sub_category_id, :photo)
  end

end

app/controllers/deltadmin/sub_categories_controller.rb
class Deltadmin::SubCategoriesController < Deltadmin::ApplicationController
  before_action :set_subcategory , only: [:show, :edit, :update, :destroy]


  def index
    @sub_categories = SubCategory.all.order(name: 'ASC')
  end

  def new
    @sub_category = SubCategory.new
  end

  def create
    @sub_category = SubCategory.new(sub_category_params)

    if @sub_category.save
      redirect_to deltadmin_sub_category_path(@sub_category)
    else
      render :new
    end
  end

  def show

  end

  def edit
  end

  def update
    if @sub_category.update(sub_category_params)
      redirect_to deltadmin_sub_category_path(@sub_category)
    else
      render :edit
    end
  end

  def destroy
    @sub_category.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to deltadmin_categories_path
  end

  private

  def set_subcategory
    @sub_category = SubCategory.find(params[:id])
  end

  def sub_category_params
    params.require(:sub_category).permit(:name, :category_id, :photo)
  end

end

app/controllers/deltadmin/users_controller.rb
class Deltadmin::UsersController < Deltadmin::ApplicationController
  before_action :set_user , only: [:show, :edit, :update, :destroy]


  def index
    @users = User.all.order(email: 'ASC')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to deltadmin_user_path(@user)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to deltadmin_user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to deltadmin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :admin)
  end

end

app/views/deltadmin/users/_form.html.erb
<div class="container">
  <div class="row">
    </div><div class="col-xs-12 col-md-offset-3 col-sm-6 padded">
      <div class="simple_form_for">
        <%= simple_form_for [:deltadmin, @user] do |f| %>
          <%= f.input :email %>
          <%= f.input :admin %>
          <%= f.submit "Sauvegarder", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>

app/views/deltadmin/users/edit.html.erb
<h2 class="text-center">Editer un Utilisateur</h2>
<%= render "deltadmin/users/form" %>

app/views/deltadmin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Utilisateurs (<%= @users.count %>)</h1>
      <table class="table">
        <thead>
          <th>ID</th>
          <th>Email</th>
          <th>Admin</th>
          <th>Editer</th>
          <th>Supprimer</th>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= link_to user.email, deltadmin_category_path(user) %></td>
            <td>
              <% if user.admin? %>
                <i style="color:green" class="fa fa-check" aria-hidden="true"></i>
              <% else %>
                <i style="color:red" class="fa fa-times" aria-hidden="true"></i>
              <% end %>
            </td>
            <td>
              <%= link_to edit_deltadmin_user_path(user) do %>
                <i class="fa fa-pencil" aria-hidden="true"></i>
              <% end %>
            </td>
            <td>
              <%= link_to deltadmin_user_path(user), method: :delete, data: { confirm: "Etes-vous sûr ?" } do %>
                <i class="fa fa-trash " aria-hidden="true"></i>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/deltadmin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1><%= @category.name %></h1>
      <div id="category-action">
        <%= link_to 'Editer', edit_deltadmin_category_path(@category), class: "btn btn-warning"  %>
        <%= link_to 'Supprimer', deltadmin_category_path(@category), method: :delete, class: "btn btn-danger" %>
      </div>
      <% if @category.photo? %>
        <div id="category-photo" class="text-center">
          <%= cl_image_tag @category.photo.path, width: 200, height: 300, crop: :fill %>
        </div>
      <% end %>
      <table class="table">
        <thead>
        <th>Sous-catégories (<%= @category.sub_categories.count %>)</th>
        </thead>
        <tbody>
          <% @category.sub_categories.each do |sub_category| %>
            <tr>
              <td><%= link_to sub_category.name, deltadmin_sub_category_path(sub_category) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>