config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  resources :categories, only: [:index, :show]
  resources :sub_categories, only: :show
  resources :products, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # ADMIN
  get "/deltadmin", to: 'deltadmin/pages#dashboard'
  namespace :deltadmin do
    resources :categories
    resources :sub_categories
    resources :users
    resources :products
  end


end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :sub_categories
  has_attachment :photo
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category , only: [:show]
  skip_before_action :authenticate_user!, only: [ :index, :show ]


  def index
    @categories = Category.all.order(name: 'ASC')
    @sub_categories = SubCategory.all
  end

  def show
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/deltadmin/categories_controller.rb
class Deltadmin::CategoriesController < Deltadmin::ApplicationController
  before_action :set_category , only: [:show, :edit, :update, :destroy]



  def index
    @categories = Category.all.order(name: 'ASC')
    @sub_categories = SubCategory.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to deltadmin_category_path(@category)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to deltadmin_category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to deltadmin_categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :photo)
  end

end

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Catégories</h1>
      <p>Delta Microscopies vous propose plus de 12 000 produits classé au sein des <%= @categories.count %> catégories proposées.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <% @categories.each do |category| %>
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-color: #999999;">
            <div class="card-category">Popular</div>
            <div class="card-description">
              <h2><%= category.name %></h2>
            </div>
            <%= link_to '', category_path(category), class: "card-link" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1><%= @category.name %></h1>
      <p><%= @category.sub_categories.count %> sous-catégories sont disponibles au sein de <%= @category.name %>.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <% @category.sub_categories.each do |sub_category| %>
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-color: #333333;">
            <div class="card-category"><%= sub_category.products.count %> produits disponibles</div>
            <div class="card-description">
              <h2><%= sub_category.name %></h2>
            </div>
            <%= link_to '', sub_category_path(sub_category), class: "card-link" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>